name: peony_project
channels: 
  - anaconda
  - pytorch
dependencies:
  - python == 3.7.0
  - numpy
  - scipy
  - tqdm
  - pandas
  - scikit-learn 
  - nltk
  - jupyter
  - pytorch
  - tensorflow
  - multiprocess
  - theano
  - seaborn
  - dash
  - plotly
  - pip:
      - chart-studio
      - docker-compose
      - pymongo
      - spacy
      - black
      - matplotlib
      - bert-serving-server
      - bert-serving-client
      - git+https://github.com/MFreidank/pysgmcmc@pytorch
      - -e .
